apiVersion: apps/v1
kind: Deployment
metadata:
  name: html
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html
  template:
    metadata:
      labels:
        app: html
    spec:
      containers:
      - name: html-voting-app
        image: your-image-name:tag
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: html
spec:
  selector:
    app: html
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

